spring:
  application:
    name: report-ms
  config:
    import: "optional:configserver:http://localhost:7777"
  profiles:
    active: qa
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  # Agregar configuración de Jackson para fechas
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  mvc:
    format:
      date: yyyy-MM-dd

# Fallback configuration
resilience4j:
  circuitbreaker:
    instances:
      companies-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

fallback:
  uri: "http://localhost:8787/companies-crud-fallback"
companies:
  base:
    url: http://localhost:8080/companies-crud
# Feign configuration

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

cloud:
  stream:
    kafka:
      binder:
        brokers: localhost:9092
    function:
      bindings:
        consumerReport-out-0:
          destination: consumerReport

logging:
  level:
    com.report.report_ms.repositories.CompaniesRepository: DEBUG
server:
  port: 7071
  servlet:
    context-path: /report-ms

# Eureka configuration

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

# También necesitas agregar estas dependencias en tu pom.xml si no las tienes
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10