
spring:
  application:
    name: report-ms
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:7777"


server:
  error:
    include-binding-errors: always
    include-message: always
  port: 7070
  servlet:
    context-path: /report-ms

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:    # Corregido: service-url debe estar bajo client
    service-url:
      defaultZone: http://localhost:8761/eureka/