spring:
  application:
    name: registry-server

server:
  port: 8761

eureka:
  client:
    # Cambiar a false porque es el servidor
    register-with-eureka: false
    fetch-registry: false
  server:
    # Configuraciones adicionales del servidor
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

# Opcional: configuración de logging para ver más detalles
logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG