spring:
  application:
    name: registry-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${random.value}