springdoc:
  swagger-ui:
    operationsSorter: method
    doc-expansion: none
    enabled: true
    path: /swagger-ui.html
    tagsSorter: alpha
  api-docs:
    enabled: true
  packagesToScan: com.MicroServicios.companies_crud
  pathsToMatch: /company/**

spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
  application:
    name: companies-crud
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:7777"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:    # Corregido: service-url debe estar bajo client
    service-url:
      defaultZone: http://localhost:8761/eureka/