springdoc:
  swagger-ui:
    operationsSorter: method
    doc-expansion: none
    enabled: true
    path: /swagger-ui.html
    tagsSorter: alpha
  api-docs:
    enabled: true
  packagesToScan: com.MicroServicios.companies_crud
  pathsToMatch: /company/**

spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
  application:
    name: companies-crud
  profiles:
    active: qa
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 6
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import: "optional:configserver:http://localhost:7777"

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /companies-crud

# Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    homePageUrl: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true


# Management Configuration
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s
  endpoints:
    web:
      exposure:
        include: '*'



# Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    # Agregar logging para Feign
    org.springframework.cloud.openfeign: DEBUG