spring:
  application:
    name: config-server
  profiles:
    active: git     # Cambiado a 'git' para activar el perfil Git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonatanmedina12/MicroService-Java-Keys.git
          default-label: main
          clone-on-start: true
        bootstrap: false    # Explícitamente configurado como false

server:
  port: 7777

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/